name: Deploy to production

on: [ push ] 

jobs:
  deploy:
    name: SCP files to server
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
          
        - name: copy file via ssh key
          uses: appleboy/scp-action@master
          with:
               host: ${{ secrets.HOST }}
               username: ${{ secrets.USERNAME }}
               port: ${{ secrets.PORT }}
               key: ${{ secrets.KEY }}
               source: "tests/*.txt"
               target: "/home/rajeshcn094"
               
        - name: Executing remote  command
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            USERNAME: ${{ secrets.USERNAME }}
            PORT: ${{ secrets.PORT }}
            KEY: ${{ secrets.KEY }}
            script: chmod 777 /home/rajeshcn094/tests
            
        #- name: permission change
        #  run: |
        #  ssh server chmod 777 /home/rajeshcn094/tests
